### ISSUE TITLE
Should we allow these annotations?

### ISSUE THREAD

**Issue by saas786** [conversionxl/phpcs-ruleset#12]
@pawelkmpt @lkraav 

We frequently use this `@inheritDoc`, so I think we should add it to our `annotationsGroups`

ref: https://github.com/conversionxl/phpcs-ruleset/blob/1483a719d2876113692d7dacd7137dac7ec0e2fe/CXL/ruleset.xml#L217

What about use of these? Should remove? replace?

`@url, @author, @uses`

**Comment by pawelkmpt** [comment]
I'd replace `@url` ([not listed on tag list](https://docs.phpdoc.org/3.0/guide/references/phpdoc/tags/index.html#tag-reference)) with `@see` and keep other tags. Not use `@author` for new commits.

**Comment by saas786** [comment]
> I'd replace `@url` ([not listed on tag list](https://docs.phpdoc.org/3.0/guide/references/phpdoc/tags/index.html#tag-reference)) with `@see` 

I am doing:

If `@url` is used in top file comment, replace it with `@link`, otherwise replace it with `@see`.

> and keep other tags. Not use `@author` for new commits.

`@author` can be removed for legacy and not used in future.

`@uses` should be replaced with `@see`,
it reminds me we have `@filter` as well I think, should we replace it with `@see` as well?

**Comment by pawelkmpt** [comment]
> If `@url` is used in top file comment, replace it with `@link`, otherwise replace it with `@see`.

👍 


> > and keep other tags. Not use `@author` for new commits.
> 
> `@author` can be removed for legacy and not used in future.

ok

> `@uses` should be replaced with `@see`, it reminds me we have `@filter` as well I think, should we replace it with `@see` as well?

I haven't seen `@filter` for a while. Just searched for few repos and didn't find any occurrence. I think this should not be just replaced as it won't provide a value in terms of quick jump to the other code. Rather replaced with method name, but it's more work.

**Comment by saas786** [comment]
`@filter`, yes you are correct, it was not from our code, but rather from other plugins.
So can ignore it.

**Comment by saas786** [comment]
Added `@inheritDoc` via https://github.com/conversionxl/phpcs-ruleset/pull/13
