### ISSUE TITLE
Slevomat Coding Standard rule "TrailingCommaInCall" error.

### ISSUE THREAD

**Issue by saas786** [conversionxl/phpcs-ruleset#3]
# Info
ERROR: Referenced sniff "SlevomatCodingStandard.Functions.TrailingCommaInCall" does not exist.

Ref: https://github.com/conversionxl/phpcs-ruleset/blob/83546e249361d2f776dde643de19414d52582cdc/CXL/ruleset.xml#L128

**Comment by lkraav** [comment]
Are you sure you have updated things correctly? This looks like Slevomat CS hasn't been installed, or...

```
cxl-wp-theme-lib $ [git:master+?][stg:6/1] ls -l vendor/slevomat/
total 0
drwxrwxr-x 1 leho crdy 214  5. okt   15:39 coding-standard
```

**Comment by saas786** [comment]
> Are you sure you have updated things correctly? This looks like Slevomat CS hasn't been installed, or...
> 
> ```
> cxl-wp-theme-lib $ [git:master+?][stg:6/1] ls -l vendor/slevomat/
> total 0
> drwxrwxr-x 1 leho crdy 214  5. okt   15:39 coding-standard
> ```

Yes, once I committed out the relevant line under **vendor/cxl/phpcs-ruleset/CXL/ruleset.xml**, it worked, no longer throws the error.

**Comment by lkraav** [comment]
It looks like last stable tag 6.4.1 has `TrailingCommaInCallSniff.php`

https://github.com/slevomat/coding-standard/tree/6.4.1/SlevomatCodingStandard/Sniffs/Functions

But current `master` does not.

What Slevomat version do you have installed?

**Comment by saas786** [comment]
> It looks like last stable tag 6.4.1 has `TrailingCommaInCallSniff.php`
> 
> https://github.com/slevomat/coding-standard/tree/6.4.1/SlevomatCodingStandard/Sniffs/Functions
> 
> But current `master` does not.
> 
> What Slevomat version do you have installed?

Seems like this: https://github.com/slevomat/coding-standard/commit/5673c4980c714b8f92f4049970e04350eed4afbb
according to `composer.lock`

**Comment by lkraav** [comment]
Why would it install from `master` https://github.com/slevomat/coding-standard/commit/5673c4980c714b8f92f4049970e04350eed4afbb

This is a local installation issue.

Our ruleset top commit has the correct `^6.4` constraint https://github.com/conversionxl/phpcs-ruleset/blob/83546e249361d2f776dde643de19414d52582cdc/composer.json#L12

**Comment by saas786** [comment]
> Why would it install from `master` [slevomat/coding-standard@5673c49](https://github.com/slevomat/coding-standard/commit/5673c4980c714b8f92f4049970e04350eed4afbb)
> 
> This is a local installation issue.
> 
> Our ruleset top commit has the correct `^6.4` constraint
> 
> https://github.com/conversionxl/phpcs-ruleset/blob/83546e249361d2f776dde643de19414d52582cdc/composer.json#L12

I think `prefer-stable` can be the cause, as 
https://github.com/conversionxl/jobs-theme/blob/b5a3921535fc96be6f9e8e1ec1a16dd9f51dadfd/composer.json
doesn't have it set to true, so seems like by default its set to **false**, 
this along with
https://github.com/conversionxl/jobs-theme/blob/b5a3921535fc96be6f9e8e1ec1a16dd9f51dadfd/composer.json#L5

### Update 01: 
Yep, `prefer-stable` seems like the cause.

Will test it out in next commit and see if it still throws error.

Dev master

![slevomat-coding-standard-dev-master](https://user-images.githubusercontent.com/1642796/109492404-c3a0f000-7aac-11eb-8a45-d8fc750b287b.png)

<hr/>
<br/>
v6.4

![slevomat-coding-standard-6 4](https://user-images.githubusercontent.com/1642796/109492413-c865a400-7aac-11eb-8ff0-03f1541bb1eb.png)

**Comment by saas786** [comment]
It no longer throws error now.

**Comment by saas786** [comment]
Not relevant anymore.

As its delivered with `v8.4.0`

Commit: https://github.com/conversionxl/phpcs-ruleset/commit/1483a719d2876113692d7dacd7137dac7ec0e2fe
