### ISSUE TITLE
Skip Squiz.Commenting.FunctionComment.Missing if @inheritDoc used

### ISSUE THREAD

**Issue by pawelkmpt** [conversionxl/phpcs-ruleset#4]
Is there a possibility to not fire these rules if `@inheritDoc` is used in the method phpdoc?

```bash
FILE: .../public/wp-content/themes/cxl-jobs/app/GravityForms/Provider.php
----------------------------------------------------------------------
FOUND 2 ERRORS AFFECTING 2 LINES
----------------------------------------------------------------------
 15 | ERROR | Missing doc comment for function register()
    |       | (Squiz.Commenting.FunctionComment.Missing)
 47 | ERROR | Missing doc comment for function boot()
    |       | (Squiz.Commenting.FunctionComment.Missing)
----------------------------------------------------------------------
```

Following code is used multiple times across the [jobs-theme](https://github.com/conversionxl/jobs-theme) and writing docs for every `Provider` is pointless.

```php
/**
 * @inheritDoc
 */
public function register(): void {}

/**
 * @inheritDoc
 */
public function boot(): void {}
```

**Comment by saas786** [comment]
@pawelkmpt still relevant?

**Comment by pawelkmpt** [comment]
I think we use `@inheritDoc` in AutomateWoo classes. Not sure if an error is still triggered though.

**Comment by saas786** [comment]
I just tested,

When class doesn't extend, inherit etc other classes.

`phpcbf` removed it, and also `PHPStorm` suggests it to be removed.

![phpstorm64_pKDIbOuz2U](https://user-images.githubusercontent.com/1642796/186674449-345ac0a6-be4b-4721-bfc3-99f61f110646.png)

But when class does extend, inherit other classes,

`phpcbf` removed it, and also `PHPStorm` doesn't suggest removal

**Comment by pawelkmpt** [comment]
> I just tested,
> 
> When class doesn't extend, inherit etc other classes.

When class doesn't extend or implement it's pointless to use `@inheritDoc`


> ![phpstorm64_pKDIbOuz2U](https://user-images.githubusercontent.com/1642796/186674449-345ac0a6-be4b-4721-bfc3-99f61f110646.png)
> 
> But when class does extend, inherit other classes,
> 
> `phpcbf` removed it, and also `PHPStorm` doesn't suggest removal

So `phpcbf` is not smart enough to detect inheritance?

Could you give me a class example?

**Comment by saas786** [comment]
> Could you give me a class example?

`src/Plugin/Features/GravityFormsPricing.php`

Ref: https://github.com/conversionxl/institute-plugin/blob/2022.08.03.1/src/Plugin/Features/GravityFormsPricing.php#L25

Applied it to `init()`

**Comment by pawelkmpt** [comment]
> `src/Plugin/Features/GravityFormsPricing.php`
> 
> Ref: https://github.com/conversionxl/institute-plugin/blob/2022.08.03.1/src/Plugin/Features/GravityFormsPricing.php#L25
> 
> Applied it to `init()`

Storm does not show any message for me. `phpcbf` only makes phpdoc oneliner.

<img width="397" alt="Screenshot 2022-08-25 at 17 33 01" src="https://user-images.githubusercontent.com/5165721/186708093-244dc751-8793-464b-ab71-aaf4ef7259b0.png">

**Comment by saas786** [comment]
> > `src/Plugin/Features/GravityFormsPricing.php`
> > Ref: [https://github.com/conversionxl/institute-plugin/blob/2022.08.03.1/src/Plugin/Features/GravityFormsPricing.php#L25](https://github.com/conversionxl/institute-plugin/blob/2022.08.03.1/src/Plugin/Features/GravityFormsPricing.php?rgh-link-date=2022-08-25T15%3A33%3A56Z#L25)
> > Applied it to `init()`
> 
> Storm does not show any message for me. `phpcbf` only makes phpdoc oneliner.
> 
> <img alt="Screenshot 2022-08-25 at 17 33 01" width="397" src="https://user-images.githubusercontent.com/5165721/186708093-244dc751-8793-464b-ab71-aaf4ef7259b0.png">

Same for me in PHPStorm.
It only suggested to remove it when used on standalone class function.

But `phpcbf` does remove it for me :(

![Loom_BQo7LKa13R](https://user-images.githubusercontent.com/1642796/186896458-054fbc70-3268-46dc-857c-f55208527738.gif)
